import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { users } from "../src/lib/server/db/schema";
import { hash } from "bcryptjs";
import { randomUUID, randomBytes } from "crypto";
import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const seedUsers = [
  // Admin users
  { email: "admin@diamondheart.app",              name: "Admin",             role: "admin" },
  { email: "mark@markmcdermott.io",               name: "Mark McDermott",    role: "admin" },

  // Regular test user
  { email: "user@diamondheart.app",               name: "Test User",         role: "user" },

  // Office users
  { email: "michael.scott@dundermifflin.com",      name: "Michael Scott",     role: "user" },
  { email: "dwight.schrute@dundermifflin.com",     name: "Dwight Schrute",    role: "user" },
  { email: "jim.halpert@dundermifflin.com",        name: "Jim Halpert",       role: "user" },
  { email: "pam.beesly@dundermifflin.com",         name: "Pam Beesly",       role: "user" },
  { email: "ryan.howard@dundermifflin.com",        name: "Ryan Howard",       role: "user" },
  { email: "andy.bernard@dundermifflin.com",       name: "Andy Bernard",      role: "user" },
  { email: "angela.martin@dundermifflin.com",      name: "Angela Martin",     role: "user" },
  { email: "kevin.malone@dundermifflin.com",       name: "Kevin Malone",      role: "user" },
  { email: "oscar.martinez@dundermifflin.com",     name: "Oscar Martinez",    role: "user" },
  { email: "stanley.hudson@dundermifflin.com",     name: "Stanley Hudson",    role: "user" },
  { email: "phyllis.vance@dundermifflin.com",      name: "Phyllis Vance",     role: "user" },
  { email: "meredith.palmer@dundermifflin.com",    name: "Meredith Palmer",   role: "user" },
  { email: "creed.bratton@dundermifflin.com",      name: "Creed Bratton",     role: "user" },
  { email: "kelly.kapoor@dundermifflin.com",       name: "Kelly Kapoor",      role: "user" },
  { email: "toby.flenderson@dundermifflin.com",    name: "Toby Flenderson",   role: "user" },
  { email: "darryl.philbin@dundermifflin.com",     name: "Darryl Philbin",    role: "user" },
  { email: "erin.hannon@dundermifflin.com",        name: "Erin Hannon",       role: "user" },
  { email: "gabe.lewis@dundermifflin.com",         name: "Gabe Lewis",        role: "user" },
  { email: "holly.flax@dundermifflin.com",         name: "Holly Flax",        role: "user" },
  { email: "jan.levinson@dundermifflin.com",       name: "Jan Levinson",      role: "user" },
];

// Generate a strong random password: lowercase, uppercase, number, 2+ special chars
function generatePassword(length = 14): string {
  const lower = "abcdefghijkmnopqrstuvwxyz";
  const upper = "ABCDEFGHJKLMNPQRSTUVWXYZ";
  const digits = "23456789";
  const special = "!@#$%&*";

  // Guarantee at least one of each, two specials
  const required = [
    lower[randomBytes(1)[0] % lower.length],
    upper[randomBytes(1)[0] % upper.length],
    digits[randomBytes(1)[0] % digits.length],
    special[randomBytes(1)[0] % special.length],
    special[randomBytes(1)[0] % special.length],
  ];

  const all = lower + upper + digits + special;
  const remaining = Array.from({ length: length - required.length }, () =>
    all[randomBytes(1)[0] % all.length]
  );

  // Shuffle
  const chars = [...required, ...remaining];
  for (let i = chars.length - 1; i > 0; i--) {
    const j = randomBytes(1)[0] % (i + 1);
    [chars[i], chars[j]] = [chars[j], chars[i]];
  }

  return chars.join("");
}

async function seed() {
  console.log("Seeding users...\n");

  // Delete existing users first (cascade will handle related data)
  await db.delete(users);
  console.log("Cleared existing users.\n");

  const credentials: { email: string; password: string; role: string }[] = [];

  for (const u of seedUsers) {
    const password = generatePassword();
    const passwordHash = await hash(password, 12);
    await db.insert(users).values({
      id: randomUUID(),
      email: u.email,
      passwordHash,
      name: u.name,
      role: u.role,
    });
    credentials.push({ email: u.email, password, role: u.role });
    console.log(`  Created ${u.role.padEnd(5)} ${u.email}`);
  }

  // Write credentials to .secrets
  const secretsPath = resolve(import.meta.dirname, "../.secrets");
  let existing = "";
  try { existing = readFileSync(secretsPath, "utf-8"); } catch {}

  // Remove any previous seed credentials block
  existing = existing.replace(/# --- SEED CREDENTIALS ---[\s\S]*# --- END SEED CREDENTIALS ---\n?/, "");

  const credBlock = [
    "# --- SEED CREDENTIALS ---",
    `# Generated by scripts/seed.ts on ${new Date().toISOString().split("T")[0]}`,
    ...credentials.map((c) => `# ${c.role.padEnd(5)} ${c.email.padEnd(45)} ${c.password}`),
    "# --- END SEED CREDENTIALS ---",
    "",
  ].join("\n");

  writeFileSync(secretsPath, existing.trimEnd() + (existing.trim() ? "\n\n" : "") + credBlock);
  console.log(`\nSeeded ${credentials.length} users.`);
  console.log("Credentials written to .secrets");
}

seed().catch(console.error);
